/*
 * GENERATED by scripts/build-tokens-css.mjs from tokens/tokens.json — do not edit by hand.
 * Tailwind 3 preset with the same utility names as the Tailwind 4 theme (bg-tb-*, text-tb-*, rounded-tb-*,
 * shadow-tb-*, font-tb-*, leading-tb-*). In tailwind.config.ts:
 *   import tbPreset from './src/design-system/<slug>/styles/tw3/preset';
 *   export default { presets: [tbPreset], content: [...] };
 * Values are var(--tb-*), so styles/tw3/index.css (which defines them) must be imported too.
 */
const preset = {
  theme: {
    extend: {
      "colors": {
        "tb-text-primary": "var(--tb-color-text-primary)",
        "tb-text-body": "var(--tb-color-text-body)",
        "tb-text-muted": "var(--tb-color-text-muted)",
        "tb-surface-page": "var(--tb-color-surface-page)",
        "tb-surface-card": "var(--tb-color-surface-card)",
        "tb-surface-muted": "var(--tb-color-surface-muted)",
        "tb-border-default": "var(--tb-color-border-default)",
        "tb-border-card": "var(--tb-color-border-card)",
        "tb-action-primary-bg": "var(--tb-color-action-primary-bg)",
        "tb-action-primary-fg": "var(--tb-color-action-primary-fg)",
        "tb-action-primary-hover-bg": "var(--tb-color-action-primary-hover-bg)",
        "tb-action-primary-disabled-bg": "var(--tb-color-action-primary-disabled-bg)",
        "tb-action-primary-disabled-fg": "var(--tb-color-action-primary-disabled-fg)",
        "tb-action-secondary-bg": "var(--tb-color-action-secondary-bg)",
        "tb-action-secondary-fg": "var(--tb-color-action-secondary-fg)",
        "tb-action-secondary-border": "var(--tb-color-action-secondary-border)",
        "tb-chip-bg": "var(--tb-color-chip-bg)",
        "tb-chip-fg": "var(--tb-color-chip-fg)",
        "tb-chip-border": "var(--tb-color-chip-border)",
        "tb-chip-selected-bg": "var(--tb-color-chip-selected-bg)",
        "tb-chip-selected-fg": "var(--tb-color-chip-selected-fg)",
        "tb-chip-selected-border": "var(--tb-color-chip-selected-border)",
        "tb-banner-bg": "var(--tb-color-banner-bg)",
        "tb-banner-fg": "var(--tb-color-banner-fg)",
        "tb-badge-bg": "var(--tb-color-badge-bg)",
        "tb-badge-fg": "var(--tb-color-badge-fg)",
        "tb-progress-fill": "var(--tb-color-progress-fill)",
        "tb-progress-track": "var(--tb-color-progress-track)",
        "tb-overlay-scrim": "var(--tb-color-overlay-scrim)",
        "tb-feedback-error": "var(--tb-color-feedback-error)",
        "tb-glow": "var(--tb-color-glow)",
        "tb-divider": "var(--tb-color-divider)"
      },
      "borderRadius": {
        "tb-button": "var(--tb-radius-button)",
        "tb-input": "var(--tb-radius-input)",
        "tb-chip": "var(--tb-radius-chip)",
        "tb-card": "var(--tb-radius-card)",
        "tb-modal": "var(--tb-radius-modal)",
        "tb-banner": "var(--tb-radius-banner)"
      },
      "boxShadow": {
        "tb-card": "var(--tb-shadow-card)",
        "tb-modal": "var(--tb-shadow-modal)",
        "tb-chip-selected": "var(--tb-shadow-chip-selected)"
      },
      "fontFamily": {
        "tb-base": "var(--tb-font-family-base)",
        "tb-heading": "var(--tb-font-family-heading)"
      },
      "fontSize": {
        "tb-h1": "var(--tb-font-size-h1)",
        "tb-h2": "var(--tb-font-size-h2)",
        "tb-h3": "var(--tb-font-size-h3)",
        "tb-body": "var(--tb-font-size-body)",
        "tb-caption": "var(--tb-font-size-caption)",
        "tb-button": "var(--tb-font-size-button)"
      },
      "fontWeight": {
        "tb-h1": "var(--tb-font-weight-h1)",
        "tb-h2": "var(--tb-font-weight-h2)",
        "tb-body": "var(--tb-font-weight-body)",
        "tb-button": "var(--tb-font-weight-button)",
        "tb-chip-selected": "var(--tb-font-weight-chip-selected)"
      },
      "lineHeight": {
        "tb-h1": "var(--tb-font-line-height-h1)",
        "tb-h2": "var(--tb-font-line-height-h2)",
        "tb-body": "var(--tb-font-line-height-body)"
      }
    },
  },
};

export default preset;
